### ISSUE TITLE
Psalm 21:16-17

### ISSUE THREAD

**Issue by bgeerdes** [catacomb-xyz/kjv-psalms-lxx#7]
Our current text:

> 16 For many dogs have compassed me, and an assembly of wicked have surrounded me.
> 17 **They have digged my hands and my feet**, they numbered all my bones, and they watched and gazed upon me.

There is no mention of "piercing".

I suggest we change *They have digged my hands and my feet* to *They pierced my hands and my feet*.

---

[Original KJV](https://www.biblegateway.com/passage/?search=Psalm+22%3A16-17&version=KJV):

> 16 For dogs have compassed me: the assembly of the wicked have inclosed me: **they pierced my hands and my feet**.
> 17 I may tell all my bones: they look and stare upon me.

[Brenton's](https://biblehub.com/sep/psalms/22.htm):

> 16 For many dogs have compassed me: the assembly of the wicked doers has beset me round: **they pierced my hands and my feet**.
> 17 They counted all my bones; and they observed and looked upon me.

[NETS](https://ccat.sas.upenn.edu/nets/edition/24-ps-nets.pdf):
> 16 because many dogs encircled me, a gathering of evildoers surrounded me. **They gouged my hands and feet**;
> 17 I counted all my bones, but they took note and observed me;

**Comment by catacomb-xyz** [comment]
Commented in PR; this is the Greek word used https://www.blueletterbible.org/lexicon/g3736/lxx/lxx/0-1/

**Comment by bgeerdes** [comment]
But does "digging" hands or feet actually make sense? NET's "gouged" makes more sense to me. It's applying the meaning of the word to the context (it being applied to a body).

I don't think "pierce" contradicts the "dig/gouge" meaning. It is even more applicable to a body. And I think it more adheres the KJV aesthetic. ("Gouged" is never used in KJV.)
